### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by chrisant996** [chrisant996/readline_win32_sample#4]
- [x] Provide custom read callback to handle VT input emulation prior to Windows 10 build 16299.
- [x] Document how, when, _and why_ to use `config_console()` and `unconfig_console()`.
- [ ] Identify how to accommodate the new timeout mechanism in Readline 8.2.
- [ ] Separate private internal Readline glue versus the public functions such as the (`un`)`config_console()` functions.

**Comment by chrisant996** [comment]
## UPDATE:

I don't plan any further updates to this readline_win32_sample repo.  The Readline project is primarily used by *nix programs.  It receives very little Win32 attention, and new commits in Readline tend to re-introduce certain kinds of problems for Win32.

The Clink project uses Readline, and until I'm able to replace Readline in Clink with an alternative, I'll keep Clink's fork of Readline working on Win32.  But I won't even try to maintain general Readline support for Win32; that would be something to discuss with the Readline maintainer(s) instead, but most likely the suggestion will be to use *nix emulation libraries on Win32 (which was not an option for Clink's needs).

> [!CAUTION]
> Clink's forks of Readline is highly bespoke and is not suitable for use outside of Clink.  It may be tempting to try to use Clink's fork of Readline anyway, but that will encounter many challenges, and I do not offer free consulting services.
